apiVersion: v1
kind: Service
metadata:
  name: kg-memory-server
  namespace: kg-memory-system
  labels:
    app.kubernetes.io/name: kg-memory-server
    app.kubernetes.io/component: server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: kg-memory-server
    app.kubernetes.io/component: server

---
apiVersion: v1
kind: Service
metadata:
  name: kg-memory-server-headless
  namespace: kg-memory-system
  labels:
    app.kubernetes.io/name: kg-memory-server
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: kg-memory-server
    app.kubernetes.io/component: server

---
# Optional: LoadBalancer service for external access
apiVersion: v1
kind: Service
metadata:
  name: kg-memory-server-lb
  namespace: kg-memory-system
  labels:
    app.kubernetes.io/name: kg-memory-server
    app.kubernetes.io/component: server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: kg-memory-server
    app.kubernetes.io/component: server