name: Build & Prepare Release

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run all tests
        run: npm run test:all

      - name: Build package
        run: npm run build

      - name: Verify TypeScript declarations
        run: |
          test -f dist/index.d.ts && echo "✓ Declaration files generated" || (echo "✗ Missing declaration files" && exit 1)

      - name: Check for vulnerabilities
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Generate SBOM
        run: npm ls --production > SBOM.txt
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            SBOM.txt
          retention-days: 7

  validate-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Validate package.json
        run: |
          npm install -g jq || true
          cat package.json | grep -q "version" && echo "✓ Package has version field" || exit 1
          cat package.json | grep -q "name" && echo "✓ Package has name field" || exit 1

      - name: Check for required files
        run: |
          test -f dist/index.js && echo "✓ Main entry point exists" || exit 1
          test -f dist/index.d.ts && echo "✓ Type definitions exist" || exit 1

      - name: Generate release notes
        id: release-notes
        run: |
          echo "# Release Artifacts Ready" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "✅ Build Status: **PASSED**" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## Build Information" >> RELEASE_NOTES.md
          echo "- Commit: ${{ github.sha }}" >> RELEASE_NOTES.md
          echo "- Branch: ${{ github.ref }}" >> RELEASE_NOTES.md
          echo "- Build ID: ${{ github.run_id }}" >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "## Package Details" >> RELEASE_NOTES.md
          cat SBOM.txt >> RELEASE_NOTES.md 2>/dev/null || echo "SBOM not available" >> RELEASE_NOTES.md
          cat RELEASE_NOTES.md

      - name: Comment PR with release readiness
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 **Release Build Ready!**\n\n✅ All checks passed\n- ✓ Linting\n- ✓ Tests\n- ✓ Build\n- ✓ Type definitions\n\nBuild artifacts are available in the workflow run. This PR is ready to merge to `main` for publishing."
            });
